/**
 * Defines internationalized constants and messages for the user interface.
 * Note that the actual GWT interfaces are generated by maven, so makes changes only to the
 * .properties files, and then run mvn gwt:i18n
 */
package org.sigmah.client.i18n;
