package org.activityinfo.server.geo;

import java.io.IOException;
import java.io.InputStream;

import com.google.appengine.api.blobstore.BlobKey;
import com.google.appengine.api.blobstore.BlobstoreInputStream;
import com.google.appengine.api.blobstore.BlobstoreService;

/**
 * Provides administrative unit geometry from the {@code aigeo} bucket in 
 * Google Cloud Storage. 
 * 
 * <p>The WKB files can are in the format generated by ActivityInfo's
 * geotools.
 */
public class CloudStorageGeometryProvider extends WkbGeometryProvider {

	private BlobstoreService blobstore;
	
	public CloudStorageGeometryProvider(BlobstoreService blobstore) {
		super();
		this.blobstore = blobstore;
	}

	@Override
	protected InputStream openInput(int adminLevelId) throws IOException {
		BlobKey blobKey = blobstore.createGsBlobKey("/gs/aigeo/" + adminLevelId + ".wkb");
		return new BlobstoreInputStream(blobKey);
	}

}
