package org.activityinfo.server.report.renderer;

import org.activityinfo.shared.report.model.ReportElement;

import java.io.IOException;
import java.io.OutputStream;

/**           
 *
 * @see org.activityinfo.shared.report.model.ReportElement
 *
 * @author Alex Bertram
 */
public interface Renderer {

    /**
     * Renders a <code>ReportElement</code> to an <code>OutputStream</code>
     *
     * @param element The <code>ReportElement</code> to render
     * @param os The <code>OutputStream</code> to which to render the element.
     * @throws IOException upon an underlying exception.
     */
    public void render(ReportElement element, OutputStream os) throws IOException;

    /**
     * Gets the MIME type of the output generated by this renderer.
     *
     * @return the MIME type of the output generated by this renderer.
     */
    String getMimeType();


    /**
     * Gets the file suffix for this type of output. Should include
     * the dot: for example, ".pdf" or ".png"
     *
     * @return the suffix to be appended to the filename of files created by this renderer.
     */
    String getFileSuffix();

}
